### ISSUE TITLE
hero padding-top

### ISSUE THREAD

**Issue by akramjonnuriddinov** [Azizbek-Boyhamdamov/Articles#2]
.hero qismida `padding-top: 326px`.

**Comment by Azizbek-Boyhamdamov** [comment]
.hero ga padding-top berishga xojat yoq align-items : center ; qilib qoyilgan vertikal oqda o'rtaga olib kelish uchun
![Screenshot_28](https://user-images.githubusercontent.com/99174734/158315792-2396bfe1-d708-4ef6-b78c-505d826fc281.png)
