### ISSUE TITLE
Button hover

### ISSUE THREAD

**Issue by akramjonnuriddinov** [Azizbek-Boyhamdamov/Articles#3]
Button uchun hover bo'lganda `opacity: 0.8` active uchun `opacity: 0.6` bo'lishi kerak.

**Comment by Azizbek-Boyhamdamov** [comment]
Button hover xolati background-color qilib RGBA => berilgan , figma faylda shunday berilgan
![Screenshot_25](https://user-images.githubusercontent.com/99174734/158314796-ca9fd57a-2f92-462e-8e81-0e39d89ee706.png)
Button active  xolati background-color qilib RGBA => berilgan , figma faylda shunday berilgan
![Screenshot_26](https://user-images.githubusercontent.com/99174734/158315023-a924b85b-c6ae-405f-8a8d-6f56c04a482f.png)
